package model;
// Generated 6/03/2016 01:29:07 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pais generated by hbm2java
 */
@Entity
@Table(name="pais"
    ,schema="public"
)
public class Pais  implements java.io.Serializable {


     private String nombrepais;

    public Pais() {
    }

    public Pais(String nombrepais) {
       this.nombrepais = nombrepais;
    }
   
     @Id 

    
    @Column(name="nombrepais", unique=true, nullable=false, length=200)
    public String getNombrepais() {
        return this.nombrepais;
    }
    
    public void setNombrepais(String nombrepais) {
        this.nombrepais = nombrepais;
    }




}


