package model;
// Generated 6/03/2016 01:29:07 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,schema="public"
)
public class Usuario  implements java.io.Serializable {


     private String correo;
     private String nombreusuario;

    public Usuario() {
    }

	
    public Usuario(String correo) {
        this.correo = correo;
    }
    public Usuario(String correo, String nombreusuario) {
       this.correo = correo;
       this.nombreusuario = nombreusuario;
    }
   
     @Id 

    
    @Column(name="correo", unique=true, nullable=false, length=200)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    
    @Column(name="nombreusuario", length=100)
    public String getNombreusuario() {
        return this.nombreusuario;
    }
    
    public void setNombreusuario(String nombreusuario) {
        this.nombreusuario = nombreusuario;
    }




}


